/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: 'https://regulskibehawiorysta.pl',
  generateRobotsTxt: false,
  additionalPaths: async () => [
    {
      loc: '/book',
      changefreq: 'weekly',
      priority: 0.9,
      lastmod: new Date().toISOString(),
    },
    {
      loc: '/kontakt',
      changefreq: 'monthly',
      priority: 0.8,
      lastmod: new Date().toISOString(),
    },
  ],
  exclude: [
    '/api/*',
    '/icon.svg',
    '/manifest.webmanifest',
    '/robots.txt',
    '/sitemap.xml',
    '/admin',
    '/admin/*',
    '/__internal/*',
    '/termin',
    '/psy',
    '/psy/*',
    '/koty',
    '/koty/*',
    '/behawiorysta-online-polska',
    '/konsultacja-behawioralna-online',
    '/qa-share-20260328-v7n3m8',
    '/urgent',
    '/quiz',
    '/produkt',
    '/od-czego-zaczac',
    '/oferta',
    '/oferta/*',
    '/jak-sie-przygotowac',
    '/jak-sie-przygotowac/*',
    '/historie',
    '/historie/*',
    '/blog/*',
    '/materialy/*',
    '/bezplatne-materialy/*',
    '/rezerwacja/*',
    '/oferta/poradniki-pdf',
    '/oferta/poradniki-pdf/*',
    '/zamow-pdf',
    '/call/*',
    '/room/*',
    '/pokoj',
    '/konto',
    '/login',
    '/dostep',
    '/problem',
    '/materialy/pobranie',
    '/bezplatne-materialy/dziekuje',
    '/niezbednik',
    '/niezbednik/*',
    '/przybornik',
  ],
  robotsTxtOptions: {
    policies: [
      { userAgent: '*', allow: '/' },
      { userAgent: '*', disallow: '/api/' },
    ],
  },
}
