export type NewsletterEditorialIssue = {
  period: string
  monthLabel: string
  title: string
  focus: string
  resourceLabel: string
  resourceHref: string
}

export const NEWSLETTER_EDITORIAL_PLAN: NewsletterEditorialIssue[] = [
  {
    period: '2026-08',
    monthLabel: 'Sierpień 2026',
    title: 'Burza, nagły hałas i bezpieczne miejsce',
    focus: 'Jak przygotować dom, czego nie sprawdzać na siłę i co obserwować po epizodzie lęku.',
    resourceLabel: 'Plan na burzę i fajerwerki',
    resourceHref: '/blog/pies-boi-sie-burzy-i-fajerwerkow',
  },
  {
    period: '2026-09',
    monthLabel: 'Wrzesień 2026',
    title: 'Powrót do rutyny bez nagłej próby',
    focus: 'Zmiana godzin wyjść, zostawanie samemu i spokojne zbieranie pierwszych nagrań.',
    resourceLabel: 'Materiały o zostawaniu samemu',
    resourceHref: '/materialy#psy',
  },
  {
    period: '2026-10',
    monthLabel: 'Październik 2026',
    title: 'Mniej światła, więcej napięcia w domu',
    focus: 'Rytm odpoczynku psa, zasoby kota i sygnały, które łatwo pomylić z nieposłuszeństwem.',
    resourceLabel: 'Materiały dla psa i kota',
    resourceHref: '/materialy',
  },
  {
    period: '2026-11',
    monthLabel: 'Listopad 2026',
    title: 'Goście, dzwonek i domowe pobudzenie',
    focus: 'Jak zmniejszyć presję przy wizytach i przygotować zwierzęciu przewidywalny plan.',
    resourceLabel: 'Plan dla psa bojącego się gości',
    resourceHref: '/materialy#psy',
  },
  {
    period: '2026-12',
    monthLabel: 'Grudzień 2026',
    title: 'Święta i Sylwester bez treningu na siłę',
    focus: 'Bezpieczeństwo, odpoczynek i decyzje, które warto podjąć przed kulminacją hałasu.',
    resourceLabel: 'Czytaj plan na hałas',
    resourceHref: '/blog/pies-boi-sie-burzy-i-fajerwerkow',
  },
  {
    period: '2027-01',
    monthLabel: 'Styczeń 2027',
    title: 'Nowy rytm po świętach',
    focus: 'Powrót do zwykłego dnia, regulacja pobudzenia i obserwacja zachowania bez szybkich etykiet.',
    resourceLabel: '30 sygnałów do obserwacji',
    resourceHref: '/materialy',
  },
  {
    period: '2027-02',
    monthLabel: 'Luty 2027',
    title: 'Bliskość, dotyk i granice zwierzęcia',
    focus: 'Kiedy kontakt pomaga, kiedy dokłada napięcia i jak zauważać wcześniejsze sygnały odmowy.',
    resourceLabel: 'Materiały o dotyku i napięciu',
    resourceHref: '/materialy#koty',
  },
  {
    period: '2027-03',
    monthLabel: 'Marzec 2027',
    title: 'Spacery po zimie bez dokładania pobudzenia',
    focus: 'Dłuższy dzień, więcej bodźców i plan powrotu do spokojniejszych spacerów.',
    resourceLabel: 'Materiały spacerowe',
    resourceHref: '/materialy#psy',
  },
  {
    period: '2027-04',
    monthLabel: 'Kwiecień 2027',
    title: 'Nowe zapachy, okna i terytorium kota',
    focus: 'Wiosenne pobudzenie, znaczenie przestrzeni i rzeczy, które warto sprawdzić przy kuwecie.',
    resourceLabel: 'Pierwszy plan przy kuwecie',
    resourceHref: '/materialy#koty',
  },
  {
    period: '2027-05',
    monthLabel: 'Maj 2027',
    title: 'Pierwsze ciepłe wyjazdy ze zwierzęciem',
    focus: 'Transport, nowe miejsce, opieka zastępcza i zachowanie rytuałów, które dają bezpieczeństwo.',
    resourceLabel: 'Plan wakacyjny dla psa',
    resourceHref: '/blog/wakacje-z-psem-plan-bez-chaosu',
  },
  {
    period: '2027-06',
    monthLabel: 'Czerwiec 2027',
    title: 'Upał, odpoczynek i mniej aktywności',
    focus: 'Jak odróżnić potrzebę ruchu od przeciążenia i dostosować dzień bez poczucia winy.',
    resourceLabel: 'Ruch czy pobudzenie',
    resourceHref: '/materialy#psy',
  },
  {
    period: '2027-07',
    monthLabel: 'Lipiec 2027',
    title: 'Opiekun zastępczy i instrukcja, która naprawdę pomaga',
    focus: 'Co spisać przed wyjazdem, jak przekazać rytm dnia i czego nie zmieniać w pierwszych dniach.',
    resourceLabel: 'Plan na wakacje',
    resourceHref: '/blog/wakacje-z-psem-plan-bez-chaosu',
  },
  {
    period: '2027-08',
    monthLabel: 'Sierpień 2027',
    title: 'Lęk przed dźwiękiem: plan przed, w trakcie i po',
    focus: 'Trzy etapy pomocy przy burzy oraz sygnały, że samo zabezpieczenie środowiska nie wystarcza.',
    resourceLabel: 'Plan na nagły hałas',
    resourceHref: '/blog/pies-boi-sie-burzy-i-fajerwerkow',
  },
  {
    period: '2027-09',
    monthLabel: 'Wrzesień 2027',
    title: 'Samotność po wakacjach: co pokazuje nagranie',
    focus: 'Różnica między odpoczynkiem, frustracją i paniką oraz pierwsze dane potrzebne do decyzji.',
    resourceLabel: 'Pies sam w domu',
    resourceHref: '/materialy#psy',
  },
  {
    period: '2027-10',
    monthLabel: 'Październik 2027',
    title: 'Dwa koty i zasoby, których nie widać na pierwszy rzut oka',
    focus: 'Przejścia, kuwety, wysokość i odpoczynek jako elementy codziennego napięcia.',
    resourceLabel: 'Konflikt między kotami',
    resourceHref: '/materialy#koty',
  },
  {
    period: '2027-11',
    monthLabel: 'Listopad 2027',
    title: 'Pies szczeka na gości: plan wejścia do domu',
    focus: 'Dystans, miejsce odpoczynku i scenariusz wizyty bez karania za komunikację.',
    resourceLabel: 'Materiały o gościach i dźwiękach',
    resourceHref: '/materialy#psy',
  },
  {
    period: '2027-12',
    monthLabel: 'Grudzień 2027',
    title: 'Kalendarz przygotowań do Sylwestra',
    focus: 'Co zrobić dwa tygodnie wcześniej, co przygotować w domu i kiedy porozmawiać z lekarzem.',
    resourceLabel: 'Plan przed Sylwestrem',
    resourceHref: '/blog/pies-boi-sie-burzy-i-fajerwerkow',
  },
  {
    period: '2028-01',
    monthLabel: 'Styczeń 2028',
    title: 'Po trudnym zdarzeniu: wracanie do równowagi',
    focus: 'Sen, apetyt, wycofanie i pobudzenie jako wskazówki do obserwacji po stresującym okresie.',
    resourceLabel: '30 zachowań do obserwacji',
    resourceHref: '/materialy',
  },
  {
    period: '2028-02',
    monthLabel: 'Luty 2028',
    title: 'Relacja bez zmuszania do kontaktu',
    focus: 'Jak budować przewidywalność i zauważać zgodę psa lub kota na dotyk i bliskość.',
    resourceLabel: 'Kot, dotyk i obrona',
    resourceHref: '/materialy#koty',
  },
  {
    period: '2028-03',
    monthLabel: 'Marzec 2028',
    title: 'Smycz jako informacja, nie tylko sprzęt',
    focus: 'Napięcie linki, dystans i tempo spaceru jako dane o stanie psa.',
    resourceLabel: 'Pies reaktywny na spacerze',
    resourceHref: '/materialy#psy',
  },
  {
    period: '2028-04',
    monthLabel: 'Kwiecień 2028',
    title: 'Kuweta po zmianie: zdrowie, miejsce i konflikt',
    focus: 'Kolejność sprawdzania przy załatwianiu poza kuwetą bez mitu o złośliwości.',
    resourceLabel: 'Kot i kuweta: pierwszy plan',
    resourceHref: '/materialy#koty',
  },
  {
    period: '2028-05',
    monthLabel: 'Maj 2028',
    title: 'Adopcja przed wakacjami: mniej presji, więcej planu',
    focus: 'Pierwsze dni, ograniczenie bodźców i przygotowanie domu przed dalszymi zmianami.',
    resourceLabel: 'Pierwsze dni po adopcji',
    resourceHref: '/materialy',
  },
  {
    period: '2028-06',
    monthLabel: 'Czerwiec 2028',
    title: 'Podróż samochodem krok po kroku',
    focus: 'Próby na krótkim odcinku, bezpieczne miejsce i plan postojów bez improwizacji.',
    resourceLabel: 'Wakacje z psem bez chaosu',
    resourceHref: '/blog/wakacje-z-psem-plan-bez-chaosu',
  },
  {
    period: '2028-07',
    monthLabel: 'Lipiec 2028',
    title: 'Dom w upał: potrzeby psa i kota',
    focus: 'Woda, chłodne strefy, aktywność o właściwej porze i obserwacja zmian zachowania.',
    resourceLabel: 'Materiały o środowisku',
    resourceHref: '/materialy',
  },
  {
    period: '2028-08',
    monthLabel: 'Sierpień 2028',
    title: 'Gdy pies nie chce wyjść po burzy',
    focus: 'Generalizacja lęku, bezpieczny dystans i powrót do spacerów bez przeciągania psa.',
    resourceLabel: 'Plan na lęk przed hałasem',
    resourceHref: '/blog/pies-boi-sie-burzy-i-fajerwerkow',
  },
  {
    period: '2028-09',
    monthLabel: 'Wrzesień 2028',
    title: 'Zmiana planu dnia bez utraty poczucia bezpieczeństwa',
    focus: 'Małe przesunięcia, stałe punkty dnia i sprawdzanie, jak zwierzę radzi sobie ze zmianą.',
    resourceLabel: 'Materiały o samotności i rutynie',
    resourceHref: '/materialy#psy',
  },
  {
    period: '2028-10',
    monthLabel: 'Październik 2028',
    title: 'Kot chowa się częściej: co zmieniło się w domu',
    focus: 'Mapa zasobów, dźwięki, zapachy i relacje jako tropy przed oceną charakteru kota.',
    resourceLabel: 'Czy Twój kot żyje w napięciu',
    resourceHref: '/materialy#koty',
  },
  {
    period: '2028-11',
    monthLabel: 'Listopad 2028',
    title: 'Pobudzenie wieczorem i problem z wyciszeniem',
    focus: 'Jak czytać rytm dnia i nie dokładać aktywności, gdy zwierzę potrzebuje odpoczynku.',
    resourceLabel: 'Ruch czy mniej pobudzenia',
    resourceHref: '/materialy#psy',
  },
  {
    period: '2028-12',
    monthLabel: 'Grudzień 2028',
    title: 'Świąteczny plan minimum dla opiekuna',
    focus: 'Trzy priorytety: bezpieczna przestrzeń, przewidywalne karmienie i mniej wymuszonych kontaktów.',
    resourceLabel: 'Materiały na trudne sytuacje',
    resourceHref: '/materialy',
  },
  {
    period: '2029-01',
    monthLabel: 'Styczeń 2029',
    title: 'Co warto zapisać przed konsultacją',
    focus: 'Krótki dziennik zachowania, nagrania i pytania, które pomagają nie zgubić najważniejszego wątku.',
    resourceLabel: 'Mapa zachowania',
    resourceHref: '/mapa-sprawy',
  },
  {
    period: '2029-02',
    monthLabel: 'Luty 2029',
    title: 'Zabawa czy napięcie między kotami',
    focus: 'Role, przerwy, blokowanie przejść i sygnały, że wspólna aktywność przestała być swobodna.',
    resourceLabel: 'Materiały o relacjach kotów',
    resourceHref: '/materialy#koty',
  },
  {
    period: '2029-03',
    monthLabel: 'Marzec 2029',
    title: 'Pierwsze wiosenne spotkania z psami',
    focus: 'Łuki, dystans i rezygnacja z powitania jako narzędzia spokojniejszego spaceru.',
    resourceLabel: 'Pies reaktywny na spacerze',
    resourceHref: '/materialy#psy',
  },
  {
    period: '2029-04',
    monthLabel: 'Kwiecień 2029',
    title: 'Nagła zmiana zachowania: od czego zacząć',
    focus: 'Zdrowie, środowisko i oś czasu problemu jako pierwsza kolejność bez zgadywania diagnozy.',
    resourceLabel: '30 sygnałów do obserwacji',
    resourceHref: '/materialy',
  },
  {
    period: '2029-05',
    monthLabel: 'Maj 2029',
    title: 'Nowe zwierzę w domu i spokojne pierwsze tygodnie',
    focus: 'Osobne zasoby, przewidywalność i tempo kontaktu dopasowane do zwierzęcia.',
    resourceLabel: 'Pierwsze dni po adopcji',
    resourceHref: '/materialy',
  },
  {
    period: '2029-06',
    monthLabel: 'Czerwiec 2029',
    title: 'Wakacyjna opieka bez zgubienia codziennego rytmu',
    focus: 'Instrukcja dla opiekuna, próba przed wyjazdem i plan awaryjny, gdy zwierzę przestaje jeść lub odpoczywać.',
    resourceLabel: 'Plan wakacyjny',
    resourceHref: '/blog/wakacje-z-psem-plan-bez-chaosu',
  },
  {
    period: '2029-07',
    monthLabel: 'Lipiec 2029',
    title: 'Trzy lata obserwacji: jak oceniać postęp bez perfekcji',
    focus: 'Mniejsze nasilenie, szybszy powrót do równowagi i lepsze decyzje jako realne miary zmiany.',
    resourceLabel: 'Wróć do Mapy zachowania',
    resourceHref: '/mapa-sprawy',
  },
]

export function getNewsletterPlanPreview(date = new Date(), limit = 3) {
  const period = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`
  const startIndex = NEWSLETTER_EDITORIAL_PLAN.findIndex((issue) => issue.period >= period)
  const safeStartIndex = startIndex >= 0 ? startIndex : Math.max(0, NEWSLETTER_EDITORIAL_PLAN.length - limit)

  return NEWSLETTER_EDITORIAL_PLAN.slice(safeStartIndex, safeStartIndex + limit)
}
