alter table public.funnel_events drop constraint if exists funnel_events_event_type_check;

alter table public.funnel_events
  add constraint funnel_events_event_type_check
    check (
      event_type in (
        'page_view',
        'view_page',
        'funnel_entry_15_min',
        'funnel_entry_60_min',
        'newsletter_signup',
        'lead_magnet_signup',
        'booking_start',
        'booking_service_selected',
        'booking_slot_selected',
        'booking_form_started',
        'booking_form_submitted',
        'payment_viewed',
        'payment_marked_pending',
        'payment_completed',
        'booking_confirmed',
        'booking_drop',
        'confirmation_viewed',
        'call_room_viewed',
        'contact_form_started',
        'contact_form_submitted',
        'hero_cta_click',
        'service_select',
        'slot_select',
        'form_start',
        'form_submit',
        'payment_start',
        'payment_reported',
        'payment_confirmed',
        'home_view',
        'dogs_page_view',
        'cta_click',
        'topic_selected',
        'slot_selected',
        'form_started',
        'payment_opened',
        'manual_pending',
        'paid',
        'confirmed',
        'reject_cancel',
        'payment_started',
        'payment_success',
        'payment_failed',
        'faq_open',
        'opinion_add',
        'room_entered',
        'quiz_completed',
        'notification_optin_submitted',
        'notification_optout_submitted'
      )
    );
